In [84]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
iris = load_iris()
iris.keys()

dict_keys(['target', 'filename', 'data', 'DESCR', 'feature_names', 'target_names'])

In [88]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [2]:
print(iris.data[0:50,:])
print(iris.target[0:50])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [3]:
def estimate_mean_cov(data):
    data_mean=data.mean(0)
    data_mean_zero=data-(data_mean)
    data_cov=(1/len(data))*np.matmul(data_mean_zero.T,data_mean_zero)
    return data_mean,data_cov


    

In [4]:
def calculate_w_b(mean,cov):    
    w=np.matmul(np.linalg.inv(cov),mean)
    b1=np.matmul(mean.T,np.linalg.inv(cov))
    b=(-0.5)*np.matmul(b1,mean)
    return w,b

In [5]:
def plot_boundery(w,b):
    x1=np.linspace(-8,12,1000)
    x2=(-w[0]/w[1])*x1-(b/w[1])
    plt.plot(x1,x2,"black")

In [6]:
#x=3.5*np.random.randn(100,2)
#y=4*np.random.randn(100,2)+4
#np.linalg.det(cov_y)

In [90]:
mean_set,cov_set=estimate_mean_cov(iris.data[0:50,:])
mean_ver,cov_ver=estimate_mean_cov(iris.data[50:100,:])
mean_vir,cov_vir=estimate_mean_cov(iris.data[100:150,:])




In [41]:
#plot_boundery(w,b)
#plt.scatter(iris.data[0:100,0],iris.data[0:100,1])
#plt.scatter(YY[:,0],YY[:,1])
#plt.scatter(XX[:,0],XX[:,1])

In [35]:
XX = np.random.multivariate_normal(mean_x, cov_x, 200)
YY= np.random.multivariate_normal(mean_y, cov_y, 200)

In [72]:
i=0
res1=np.zeros((100,))
res2=np.zeros((100,))
for item in iris.data[:100,:]:
    xx=np.matmul((item-mean_x).T,cov_x)
    res1[i]=np.matmul(xx,(item-mean_x))
    yy=np.matmul((item-mean_y).T,cov_y)
    res2[i]=np.matmul(yy,(item-mean_y))
    i+=1


In [83]:
xxr=np.array([[1,2],[4,10]])
np.argmax((xxr),axis=1)

array([1, 1], dtype=int64)

In [39]:
cov_x
x1=np.linspace(-8,12,10)
x1

array([-8.        , -5.77777778, -3.55555556, -1.33333333,  0.88888889,
        3.11111111,  5.33333333,  7.55555556,  9.77777778, 12.        ])